//Generated by TurboLink CodeGenerator, do not edit!
#include "GreeterMarshaling.h"

void GRPC_TO_TURBOLINK(const ::Greeter::HelloRequest* in, FGrpcGreeterHelloRequest* out)
{
    out->Name=UTF8_TO_TCHAR(in->name().c_str());
}

void TURBOLINK_TO_GRPC(const FGrpcGreeterHelloRequest* in, ::Greeter::HelloRequest* out)
{
    out->set_name(TCHAR_TO_UTF8(*(in->Name)));
}
void GRPC_TO_TURBOLINK(const ::Greeter::HelloResponse* in, FGrpcGreeterHelloResponse* out)
{
    out->ReplyMessage=UTF8_TO_TCHAR(in->reply_message().c_str());
}

void TURBOLINK_TO_GRPC(const FGrpcGreeterHelloResponse* in, ::Greeter::HelloResponse* out)
{
    out->set_reply_message(TCHAR_TO_UTF8(*(in->ReplyMessage)));
}
