//Generated by TurboLink CodeGenerator, do not edit!
#include "GreeterService_Private.h"

void UGreeterServiceHelloLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcGreeterHelloResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnHelloResponse.RemoveDynamic(this, &UGreeterServiceHelloLambdaWrapper::OnResponse);
}

