//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SGreeter/GreeterMessage.h"
#include "GreeterClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnGreeterServiceHelloResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcGreeterHelloResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UGreeterServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnGreeterServiceHelloResponse OnHelloResponse;

public:
	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitHello();

	UFUNCTION(BlueprintCallable)
	void Hello(FGrpcContextHandle Handle, const FGrpcGreeterHelloRequest& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable)
	void TryCancel(FGrpcContextHandle Handle);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnTimeServiceTicktokResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcGreeterNowResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnTimeServiceWatchResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcGreeterNowResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UTimeServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnTimeServiceTicktokResponse OnTicktokResponse;

	UPROPERTY(BlueprintAssignable)
	FOnTimeServiceWatchResponse OnWatchResponse;

public:
	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitTicktok();

	UFUNCTION(BlueprintCallable)
	void Ticktok(FGrpcContextHandle Handle, const FGrpcGreeterTicktokRequest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitWatch();

	UFUNCTION(BlueprintCallable)
	void Watch(FGrpcContextHandle Handle, const FGrpcGreeterWatchRequest& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable)
	void TryCancel(FGrpcContextHandle Handle);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnStreamServiceLotsOfRepliesResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcGreeterHelloResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnStreamServiceBidiHelloResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcGreeterHelloResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UStreamServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnStreamServiceLotsOfRepliesResponse OnLotsOfRepliesResponse;

	UPROPERTY(BlueprintAssignable)
	FOnStreamServiceBidiHelloResponse OnBidiHelloResponse;

public:
	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitLotsOfReplies();

	UFUNCTION(BlueprintCallable)
	void LotsOfReplies(FGrpcContextHandle Handle, const FGrpcGreeterHelloRequest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitBidiHello();

	UFUNCTION(BlueprintCallable)
	void BidiHello(FGrpcContextHandle Handle, const FGrpcGreeterHelloRequest& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable)
	void TryCancel(FGrpcContextHandle Handle);
};

