//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "GreeterMessage.generated.h"


USTRUCT(BlueprintType, meta = (DisplayName="Greeter.HelloRequest"))
struct FGrpcGreeterHelloRequest : public FGrpcMessage
{
    GENERATED_USTRUCT_BODY()

    UPROPERTY(BlueprintReadWrite)
    FString Name;
};

USTRUCT(BlueprintType, meta = (DisplayName="Greeter.HelloResponse"))
struct FGrpcGreeterHelloResponse : public FGrpcMessage
{
    GENERATED_USTRUCT_BODY()

    UPROPERTY(BlueprintReadWrite)
    FString ReplyMessage;
};

