//Generated by TurboLink CodeGenerator, do not edit!
#include "SGreeter/GreeterMessage.h"
#include "TurboLinkGrpcContext.h"
#include "pb/hello.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::Greeter::HelloRequest* in, FGrpcGreeterHelloRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterHelloRequest* in, ::Greeter::HelloRequest* out);

void GRPC_TO_TURBOLINK(const ::Greeter::HelloResponse* in, FGrpcGreeterHelloResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterHelloResponse* in, ::Greeter::HelloResponse* out);

typedef grpc::ClientAsyncResponseReader<::Greeter::HelloResponse> GreeterService_Hello_ReaderWriter;
