//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SGreeter/GreeterMessage.h"
#include "SGreeter/GreeterMarshaling.h"
class GrpcContext_GreeterService_Hello : public GrpcContext_Ping_Pong<GreeterService_Hello_ReaderWriter, ::Greeter::HelloResponse>
{
	friend class UGreeterServiceClient;
	typedef GrpcContext_Ping_Pong<GreeterService_Hello_ReaderWriter, ::Greeter::HelloResponse> Super;

private:
	void Call(const FGrpcGreeterHelloRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_GreeterService_Hello(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

