//Generated by TurboLink CodeGenerator, do not edit!
#include "SGreeter/GreeterClient.h"
#include "SGreeter/GreeterService.h"
#include "GreeterContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UGreeterServiceClient::InitHello()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_GreeterService_Hello>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UGreeterServiceClient::Hello(FGrpcContextHandle Handle, const FGrpcGreeterHelloRequest& Request)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextHello = StaticCastSharedPtr<GrpcContext_GreeterService_Hello>(*context);
		contextHello->Call(Request);
	}
}
void UGreeterServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UGreeterServiceClient::Shutdown()
{
	OnHelloResponse.Clear();
	Super::Shutdown();
}
